name: PR Review

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'The number of the pull request to review'
        required: true
        type: number

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Run review script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_NUMBER: ${{ github.event.inputs.pull_request_number }}
      run: python scripts/review_pr.py
